// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSerial(arg1) {
  return window['go']['main']['App']['ConnectSerial'](arg1);
}

export function DisconnectSerial() {
  return window['go']['main']['App']['DisconnectSerial']();
}

export function GetAirConditionerState() {
  return window['go']['main']['App']['GetAirConditionerState']();
}

export function GetAvailablePorts() {
  return window['go']['main']['App']['GetAvailablePorts']();
}

export function SetFanSpeed(arg1) {
  return window['go']['main']['App']['SetFanSpeed'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SetPower(arg1) {
  return window['go']['main']['App']['SetPower'](arg1);
}

export function SetSwing(arg1) {
  return window['go']['main']['App']['SetSwing'](arg1);
}

export function SetTemperature(arg1) {
  return window['go']['main']['App']['SetTemperature'](arg1);
}
