// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';

export function CalculateFrameCheck(arg1:Array<number>):Promise<number>;

export function ConnectSerial(arg1:main.SerialConfig):Promise<void>;

export function ConstructResponse(arg1:number,arg2:number,arg3:number,arg4:Array<number>):Promise<Array<number>>;

export function DisconnectSerial():Promise<void>;

export function GetAirConditionerState():Promise<main.AirConditioner>;

export function GetAvailablePorts():Promise<Array<string>>;

export function GetReturnStatus(arg1:number,arg2:number):Promise<number>;

export function ReadFrame(arg1:Array<number>,arg2:time.Duration):Promise<Array<number>>;

export function SetFanSpeed(arg1:string):Promise<main.AirConditioner>;

export function SetMode(arg1:string):Promise<main.AirConditioner>;

export function SetModel(arg1:number):Promise<main.AirConditioner>;

export function SetPower(arg1:boolean):Promise<main.AirConditioner>;

export function SetSwing(arg1:boolean):Promise<main.AirConditioner>;

export function SetTemperature(arg1:number):Promise<main.AirConditioner>;

export function StartProtocolListener():Promise<void>;

export function VerifyFrameChecksum(arg1:Array<number>):Promise<boolean>;
