// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectMQTT():Promise<void>;

export function DisconnectMQTT():Promise<void>;

export function GetAirConditionerState():Promise<main.AirConditioner>;

export function GetCapabilities():Promise<main.CapabilityInfo>;

export function GetMQTTConfig():Promise<main.MQTTConfig>;

export function GetMQTTStatus():Promise<boolean>;

export function PublishDiscovery():Promise<void>;

export function PublishStatus():Promise<void>;

export function SetFanSpeed(arg1:string):Promise<main.AirConditioner>;

export function SetMode(arg1:string):Promise<main.AirConditioner>;

export function SetModel(arg1:number):Promise<main.AirConditioner>;

export function SetPower(arg1:boolean):Promise<main.AirConditioner>;

export function SetRoomTemperature(arg1:number):Promise<main.AirConditioner>;

export function SetSwing(arg1:boolean):Promise<main.AirConditioner>;

export function SetTemperature(arg1:number):Promise<main.AirConditioner>;

export function UpdateMQTTConfig(arg1:main.MQTTConfig):Promise<void>;
