// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectMQTT() {
  return window['go']['main']['App']['ConnectMQTT']();
}

export function DisconnectMQTT() {
  return window['go']['main']['App']['DisconnectMQTT']();
}

export function GetAirConditionerState() {
  return window['go']['main']['App']['GetAirConditionerState']();
}

export function GetCapabilities() {
  return window['go']['main']['App']['GetCapabilities']();
}

export function GetMQTTConfig() {
  return window['go']['main']['App']['GetMQTTConfig']();
}

export function GetMQTTStatus() {
  return window['go']['main']['App']['GetMQTTStatus']();
}

export function PublishDiscovery() {
  return window['go']['main']['App']['PublishDiscovery']();
}

export function PublishStatus() {
  return window['go']['main']['App']['PublishStatus']();
}

export function SetFanSpeed(arg1) {
  return window['go']['main']['App']['SetFanSpeed'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetPower(arg1) {
  return window['go']['main']['App']['SetPower'](arg1);
}

export function SetRoomTemperature(arg1) {
  return window['go']['main']['App']['SetRoomTemperature'](arg1);
}

export function SetSwing(arg1) {
  return window['go']['main']['App']['SetSwing'](arg1);
}

export function SetTemperature(arg1) {
  return window['go']['main']['App']['SetTemperature'](arg1);
}

export function UpdateMQTTConfig(arg1) {
  return window['go']['main']['App']['UpdateMQTTConfig'](arg1);
}
